version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    ignore:
      - dependency-name: "jose"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "openid-client"
        update-types: [ "version-update:semver-major" ]
    commit-message:
      prefix: chore
    groups:
      npm-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: chore
    groups:
      docker-updates:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      github-actions-updates:
        patterns:
          - "*"